### ISSUE TITLE
Consider allowing `anyOf` [...] {"type": "null"} to represent a nullable object

### ISSUE THREAD

**Issue by bruno-f-cruz** [bonsai-rx/sgen#12]
Consider the following: 

```json 

"too": {
         "anyOf": [
            {
               "type": "int"
            },
            {
               "type": "null"
            }
         ],
         "default": "null"
      },
```

The current sgen fails to convert and just creates an empty "foo" class. I would suggest to:
if only two members are found inside one of the anyOf (say T and null) the created type should be of Nullable<T>. If multiple types are found, consider creating a wrapper class to allow polymorphic behavior and make that type nullable.

**Comment by bruno-f-cruz** [comment]
On second thought this should probably only be relevant for primitive and numeric types eg: int, which should be instantiated as int?.
For all generic types, the ideal situation is to actually use the null type in the schema as a way to enforce validation since, in bonsai, all objects can be null, having an allowed null type is not strictly necessary. I propose to simply ignore the typing and perhaps add a new atribute to the class that keeps that information which we might want to leverage later.

**Comment by bruno-f-cruz** [comment]
For instance, one could use https://www.newtonsoft.com/json/help/html/NullValueHandlingIgnore.htm to make sure that on serialization, properties that are not defined in an object, but that should not be allowed to be None, and are not required, should not be added to the output file.

**Comment by glopesdev** [comment]
This is being tracked upstream at https://github.com/pydantic/pydantic/issues/7161. We should fix this either on pydantic or NJsonSchema side to ensure long-term compatibility.
